#!/bin/bash

# Copyright (C) 2026 Kendall Tauser
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

declare -r branch=$(git for-each-ref --format='%(refname:short)' refs/heads/ | head -1)

cat <<INFO

============================================================================================
| Git Commit Synopsis
============================================================================================
| Current Branch:       ${branch}
| Current Revision:     $(git rev-parse HEAD)
| Remote Revision:      $(git rev-parse remotes/origin/${branch})
| Current Remote:       origin
============================================================================================

INFO

# Pull down old commits before committing here.
#git pull origin ${branch}
