
exec-once = [workspace 2 silent] $term
exec-once = [workspace 3 silent] $editor
exec-once = [workspace 5 silent] $editor
exec-once = [workspace 4 silent] $browser
exec-once = [workspace 1 silent] $browser
