
exec-once = [workspace 2 silent DP-1] $term
exec-once = [workspace 3 silent DP-2] $editor
exec-once = [workspace 5 silent DP-1] $editor
exec-once = [workspace 4 silent DP-1] $browser
exec-once = [workspace 1 silent DP-2] $browser
